In [1]:
import numpy as np

In [3]:
#Array de duas dimensoes

array = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15],
                  [16, 17, 18, 19, 20]])

array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
#Fatiar as duas primeiras linhas

fatiar_linhas = array[0:3,:]
fatiar_linhas

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [10]:
#Fatiar as 3 primeiras colunas

fatiar_colunas = array[:,0:3]
fatiar_colunas

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [11]:
subarray_central = array[1:3, 1:3]
subarray_central

array([[ 7,  8],
       [12, 13]])

In [13]:
subarray_lateral = array[2:4, 3:5]
subarray_lateral

array([[14, 15],
       [19, 20]])

In [14]:
#Modificar um subarray

array[1:3, 1:3] = [[99, 100], [101, 102]]
array


array([[  1,   2,   3,   4,   5],
       [  6,  99, 100,   9,  10],
       [ 11, 101, 102,  14,  15],
       [ 16,  17,  18,  19,  20]])