In [1]:
import numpy as np

In [ ]:


array = np.array([1, 2, 3, 4, 5, 6])
array

array([1, 2, 3, 4, 5, 6])

In [3]:
#Dividir arrays

array_dividido = np.split(array, 3)
array_dividido

[array([1, 2]), array([3, 4]), array([5, 6])]

In [4]:
for i, value in enumerate(array_dividido):
    print(f'Parte {i+1} --> {value}')

Parte 1 --> [1 2]
Parte 2 --> [3 4]
Parte 3 --> [5 6]


In [24]:
#Criar um array 1D com temperaturas diárias de um mês (28 dias)

temperaturas = np.array([
    23, 27, 30, 19, 25, 33, 21, 22, 28, 35,
    18, 29, 20, 32, 24, 26, 27, 19, 30, 34,
    22, 23, 31, 25, 28, 16, 29, 21
])

temperaturas


array([23, 27, 30, 19, 25, 33, 21, 22, 28, 35, 18, 29, 20, 32, 24, 26, 27,
       19, 30, 34, 22, 23, 31, 25, 28, 16, 29, 21])

In [25]:
#Divindido as temperaturas em 4 semanas
#Esta função só divide se o resultado for número inteiro. Exemplo: 28 dias / 4 = 7. Ou seja, 4 arrays com 7 temperaturas. 
#Se tentar dividir 30 / 4 = 7,5. Isto causará um erro na função
#O np.split só funciona quando o array pode ser dividido em partes iguais.


semanas = np.split(temperaturas, 4)
semanas


[array([23, 27, 30, 19, 25, 33, 21]),
 array([22, 28, 35, 18, 29, 20, 32]),
 array([24, 26, 27, 19, 30, 34, 22]),
 array([23, 31, 25, 28, 16, 29, 21])]

In [26]:
for i, value in enumerate(semanas):
    print(f'Semana {i+1}: {value}')

Semana 1: [23 27 30 19 25 33 21]
Semana 2: [22 28 35 18 29 20 32]
Semana 3: [24 26 27 19 30 34 22]
Semana 4: [23 31 25 28 16 29 21]


In [29]:
#Média de temperatura por semana

media_semana = [np.mean(semana) for semana in semanas]
media_semana


[25.428571428571427, 26.285714285714285, 26.0, 24.714285714285715]

In [30]:
for i, value in enumerate(media_semana):
    print(f'Média da semana {i+1}: {value:.2f}°C.')

Média da semana 1: 25.43°C.
Média da semana 2: 26.29°C.
Média da semana 3: 26.00°C.
Média da semana 4: 24.71°C.
