In [1]:
import numpy as np

In [8]:
array = np.array([10, 20, 30, 40, 50])
array

array([10, 20, 30, 40, 50])

In [9]:
#Pesquisar a posição do valor 30

posicao = np.where(array==30)
posicao

(array([2], dtype=int64),)

In [20]:
#Criar um array com nota de alunos

notas = np.array([19, 11.5, 20, 19, 17, 16, 13, 19, 15, 11, 20])
notas

array([19. , 11.5, 20. , 19. , 17. , 16. , 13. , 19. , 15. , 11. , 20. ])

In [21]:
#Pesquisar alunos aprovados (nota > 12)

aprovados = np.where(notas > 12)
aprovados

(array([ 0,  2,  3,  4,  5,  6,  7,  8, 10], dtype=int64),)

In [22]:
#Para ter a informação das notas e não os índices

notas[aprovados]

array([19., 20., 19., 17., 16., 13., 19., 15., 20.])

In [23]:
#Pesquisar a nota máxima

nota_maxima = np.max(notas)
nota_maxima

20.0

In [24]:
#índice da nota máxima

indice_maximo = np.argmax(notas)
indice_maximo

2