In [1]:
import numpy as np

In [7]:
array_1d = np.array([1, 2, 3, 4, 5, 6])
print(array_1d.ndim) #Número de dimensões
print(array_1d.shape) #Formato do array
array_1d


#Array de uma dimnesão. Comum em lista de dados, como séries temporais ou coleções.

1
(6,)


array([1, 2, 3, 4, 5, 6])

In [11]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d.ndim) #Número de dimensões
print(array_2d.shape) #Formato do array
array_2d

#Agora é uma matriz com 2 dimensões. 2 linhas e 3 colunas.
#Comum em matrizes, tabelas de dados e imagens em escalas de cinza.

2
(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array_3d = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]]])
print(array_3d.ndim)
print(array_3d.shape)
print(array_3d[0][2][1])
array_3d

#Imagens com cores (RGB)

3
(1, 4, 2)
6


array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])