In [2]:
import numpy as np

In [5]:
array = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print(array.ndim)
print(array.shape)
array

2
(3, 3)


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [9]:
#Buscar elemento na linha 1 e coluna 2.

print(array[1][2])

#OU

elemento = array[1, 2]
elemento

60


60

In [11]:
#Dados da primeira linha

linha_0 = array[0]
linha_0

array([10, 20, 30])

In [12]:
#Dados só da coluna

coluna_1 = array[:, 1]
coluna_1

array([20, 50, 80])

In [14]:
#Fatiamento para obter um subarray
#Linha de 0 a 1 | Coluna 1 a 2

subarray = array[0:2, 1:3]
subarray

array([[20, 30],
       [50, 60]])

In [ ]:
#Retorona resultado booleano
#Serve para filtrar os dados

mascara = array>50
mascara

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [16]:
elementos_maiores_50 = array[mascara]
elementos_maiores_50

array([60, 70, 80, 90])

In [18]:
#Modificar elemento na linha 1, coluna 1
#Atribuir o valor 100

array[1, 1] = 100
array


array([[ 10,  20,  30],
       [ 40, 100,  60],
       [ 70,  80,  90]])