In [1]:
import numpy as np

In [2]:
array = np.array([1, 2, 3, 4, 5])
array

array([1, 2, 3, 4, 5])

In [3]:
#Funcao adicao

soma = np.add(array, 10)
soma

array([11, 12, 13, 14, 15])

In [4]:
#Subtracao

subtracao = np.subtract(array, 5)
subtracao

array([-4, -3, -2, -1,  0])

In [5]:
#Multiplicacao

produto = np.multiply(array, 2)
produto

array([ 2,  4,  6,  8, 10])

In [6]:
#Divisao

divisao = np.divide(array, 2)
divisao

array([0.5, 1. , 1.5, 2. , 2.5])

In [ ]:
#Funcoes trigonométricas

seno = np.sin(array)
seno

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [8]:
cosseno = np.cos(array)
cosseno

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [9]:
#Funcoes estatisticas

media = np.mean(array)
media

3.0

In [10]:
#Desvio padrao

d_p = np.std(array)
d_p

1.4142135623730951

In [12]:
#Funcoes de comparacao
#Retorna valores booleanos

array_3 = array>3
array_3

array([False, False, False,  True,  True])

In [14]:
#Combinar funcoes
#Primeira funcao: calcula a raiz quadrada de cada elemento do array
#Segunda funcao: eleva cada elemento ao quadrado - é equivalente a (array ** 2)

resultado = np.sqrt(array) + np.power(array, 2)
resultado

array([ 2.        ,  5.41421356, 10.73205081, 18.        , 27.23606798])

In [16]:
#Funcoes exponenciais
# calcula 𝑒𝑥 para cada elemento de x, onde 𝑒 é o número de Euler ≈ 2.71828

exponencial = np.exp(array)
exponencial

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [17]:
#Funcao de logaritmo 

logaritimo = np.log(array)
logaritimo

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [18]:
#Funcao de arredondamento

arredondado = np.round(array / 2)
arredondado

array([0., 1., 2., 2., 2.])

In [19]:
#Funcao de potencia

potencia = np.power(array, 3)
potencia

array([  1,   8,  27,  64, 125], dtype=int32)