Copy 
- Uma nova cópia do array é criada em memória. Isso significa que as duas matrizes (original e cópia) são independentes uma da outra.


View
- Não é criada em uma nova cópia na memória. A view compartilha os mesmos dados que o array original.

In [2]:
import numpy as np

In [3]:
array_original = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])
array_original

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
#1- Cópia rasa (View)
#A view altera o array original. Não preserva os dados.

array_view = array_original[1: , 1:]
array_view


array([[5, 6],
       [8, 9]])

In [5]:
array_view[0,0] = 99
array_view

array([[99,  6],
       [ 8,  9]])

In [ ]:
#Foi alterado pela array view
array_original

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]])

In [7]:
#2- Copy
#Copia e preserva o array original

array_copia = array_original.copy()
array_copia

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]])

In [15]:
#Alterando dados do array copia

array_copia[0,0] = 100
print('Este é o array cópia modificado:\n', array_copia)
print('Este é o array original e continua sem alterações: \n',array_original)

Este é o array cópia modificado:
 [[100   2   3]
 [  4  99   6]
 [  7   8   9]]
Este é o array original e continua sem alterações: 
 [[ 1  2  3]
 [ 4 99  6]
 [ 7  8  9]]
