In [1]:
import numpy as np

In [2]:
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
#1- iteração simples usando o loop for

for linha in array:
    print(linha)

[1 2 3]
[4 5 6]
[7 8 9]


In [9]:
#2- iteração simples usando o loop for

for linha in array:
    for elemento in linha:
        print(elemento, end = ', ')

1, 2, 3, 4, 5, 6, 7, 8, 9, 

In [ ]:
#3- Usando o np.nditer para uma iteração mais eficiente.
#Mesmo resultado com apenas um ciclo FOR

for valor in np.nditer(array):
    print(valor, end= ', ')

1, 2, 3, 4, 5, 6, 7, 8, 9, 

In [12]:
#4- Iteração com condição

for valor in np.nditer(array):
    if valor > 5:
        print(valor, end= ', ')

6, 7, 8, 9, 

In [ ]:
#Iteração com índices
# Array.shape retorna uma tupla com as dimensões do array
# array.shape[0] → número de linhas.
# array.shape[1] → número de colunas.

for i in range(array.shape[0]): #iterando sobre as linhas
    for j in range(array.shape[1]):
        print(f'Elemento na posição ({i}, {j}): {array[i, j]}')

Elemento na posição (0, 0): 1
Elemento na posição (0, 1): 2
Elemento na posição (0, 2): 3
Elemento na posição (1, 0): 4
Elemento na posição (1, 1): 5
Elemento na posição (1, 2): 6
Elemento na posição (2, 0): 7
Elemento na posição (2, 1): 8
Elemento na posição (2, 2): 9
