In [2]:
import numpy as np

In [3]:
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7])

In [ ]:
#Concatenando os arrays

novo_array = np.concatenate((array1, array2))
novo_array


array([1, 2, 3, 4, 5, 6, 7])

In [8]:
#Criando arrays com nomes e notas

nomes = np.array(['Alice', 'João', 'Marcos'])
notas_matematica = np.array([18, 17.5, 20])
notas_fisica = np.array([19, 18, 19])

In [11]:
#Usando np.vstack para empilhar verticalmente os dados

dados_estudantes = np.vstack((nomes,notas_matematica, notas_fisica))
dados_estudantes


array([['Alice', 'João', 'Marcos'],
       ['18.0', '17.5', '20.0'],
       ['19', '18', '19']], dtype='<U32')

In [12]:
#Usando np.hstack para empilhar horizontalmente

matriz_notas = np.column_stack((notas_matematica, notas_fisica))
matriz_notas

array([[18. , 19. ],
       [17.5, 18. ],
       [20. , 19. ]])

In [13]:
#Adicionar uma nova coluna com a média das notas

media_notas = np.mean(matriz_notas, axis=1)
matriz_final = np.column_stack((matriz_notas, media_notas))
matriz_final

array([[18.  , 19.  , 18.5 ],
       [17.5 , 18.  , 17.75],
       [20.  , 19.  , 19.5 ]])